const allWorkshops = [
  {
    id: 1,
    title: "Machine Learning using Python",
    instructor: "Prof. Ganesh Ramakrishnan",
    date: "2025-04-16",
    location: "IIT Bombay",
    seats: 35,
    seatsLeft: 10,
    category: "Python",
    level: "Intermediate",
    duration: "2 Days",
    description: "Build strong ML foundations with Python, datasets, and practical model training.",
  },
  {
    id: 2,
    title: "Data Mining using Python",
    instructor: "Prof. Soumen Chakrabarti",
    date: "2025-04-27",
    location: "IIT Bombay",
    seats: 40,
    seatsLeft: 15,
    category: "Python",
    level: "Intermediate",
    duration: "1 Day",
    description: "Learn patterns, clustering, classification, and mining workflows using Python.",
  },
  {
    id: 3,
    title: "Thermal Sciences and CFD Applications",
    instructor: "Prof. Sameer Khandekar",
    date: "2025-04-30",
    location: "IIT Kanpur",
    seats: 20,
    seatsLeft: 3,
    category: "OpenFOAM",
    level: "Advanced",
    duration: "2 Days",
    description: "Understand CFD simulation workflows and thermal science use-cases with OpenFOAM.",
  },
  {
    id: 4,
    title: "Introduction to Scilab",
    instructor: "Prof. Kannan M. Moudgalya",
    date: "2025-05-02",
    location: "IIT Bombay",
    seats: 50,
    seatsLeft: 21,
    category: "Scilab",
    level: "Beginner",
    duration: "1 Day",
    description: "Start using Scilab for numerical computing, plotting, and engineering workflows.",
  },
  {
    id: 5,
    title: "Arduino for Beginners",
    instructor: "Prof. R. Venkatesh",
    date: "2025-05-08",
    location: "IIT Madras",
    seats: 45,
    seatsLeft: 12,
    category: "Arduino",
    level: "Beginner",
    duration: "2 Days",
    description: "Learn sensors, LEDs, actuators, and build interactive hardware projects.",
  },
  {
    id: 6,
    title: "Deep Learning Foundations",
    instructor: "Prof. Pushpak Bhattacharyya",
    date: "2025-05-12",
    location: "IIT Bombay",
    seats: 60,
    seatsLeft: 18,
    category: "AI/ML",
    level: "Intermediate",
    duration: "2 Days",
    description: "Explore neural networks, training concepts, and practical deep learning intuition.",
  },
  {
    id: 7,
    title: "MATLAB for Signal Processing",
    instructor: "Prof. Anil Kumar",
    date: "2025-05-18",
    location: "IIT Delhi",
    seats: 30,
    seatsLeft: 9,
    category: "MATLAB",
    level: "Intermediate",
    duration: "1 Day",
    description: "Work with filtering, transforms, and signal analysis in MATLAB.",
  },
  {
    id: 8,
    title: "Computer Vision with Python",
    instructor: "Prof. Debdoot Sheet",
    date: "2025-05-21",
    location: "IIT Kharagpur",
    seats: 38,
    seatsLeft: 7,
    category: "AI/ML",
    level: "Intermediate",
    duration: "2 Days",
    description: "Image processing, OpenCV pipelines, detection basics, and real-world CV tasks.",
  },
  {
    id: 9,
    title: "Numerical Methods using Scilab",
    instructor: "Prof. S. N. Mahesh",
    date: "2025-05-25",
    location: "IIT Hyderabad",
    seats: 42,
    seatsLeft: 16,
    category: "Scilab",
    level: "Beginner",
    duration: "1 Day",
    description: "Solve root-finding, interpolation, integration, and numerical analysis problems.",
  },
  {
    id: 10,
    title: "OpenFOAM for Beginners",
    instructor: "Prof. Arvind Pattamatta",
    date: "2025-05-28",
    location: "IIT Madras",
    seats: 28,
    seatsLeft: 5,
    category: "OpenFOAM",
    level: "Beginner",
    duration: "2 Days",
    description: "Get started with meshing, cases, boundary conditions, and simulation setup.",
  },
  {
    id: 11,
    title: "Python for Scientific Computing",
    instructor: "Prof. Balaram Das",
    date: "2025-06-02",
    location: "IIT Roorkee",
    seats: 55,
    seatsLeft: 20,
    category: "Python",
    level: "Beginner",
    duration: "1 Day",
    description: "Use NumPy, Pandas, Matplotlib, and Jupyter for scientific workflows.",
  },
  {
    id: 12,
    title: "Natural Language Processing Basics",
    instructor: "Prof. Monojit Choudhury",
    date: "2025-06-06",
    location: "IIT Delhi",
    seats: 48,
    seatsLeft: 14,
    category: "AI/ML",
    level: "Intermediate",
    duration: "2 Days",
    description: "Text preprocessing, embeddings, classification, and intro to language models.",
  },
  {
    id: 13,
    title: "Embedded Systems with Arduino",
    instructor: "Prof. K. Raghunandan",
    date: "2025-06-09",
    location: "IIT Guwahati",
    seats: 32,
    seatsLeft: 11,
    category: "Arduino",
    level: "Intermediate",
    duration: "2 Days",
    description: "Design practical embedded projects and interface multiple hardware modules.",
  },
  {
    id: 14,
    title: "Advanced CFD Workflows",
    instructor: "Prof. S. A. Narasimhan",
    date: "2025-06-13",
    location: "IIT Kanpur",
    seats: 22,
    seatsLeft: 2,
    category: "OpenFOAM",
    level: "Advanced",
    duration: "3 Days",
    description: "Dive into advanced CFD strategies, solver settings, and engineering validation.",
  },
  {
    id: 15,
    title: "Data Visualization in Python",
    instructor: "Prof. Chetan Arora",
    date: "2025-06-18",
    location: "IIT Delhi",
    seats: 44,
    seatsLeft: 17,
    category: "Python",
    level: "Beginner",
    duration: "1 Day",
    description: "Create compelling charts, dashboards, and storytelling visuals using Python.",
  },
  {
    id: 16,
    title: "Control Systems in Scilab",
    instructor: "Prof. Deepak Khemani",
    date: "2025-06-22",
    location: "IIT Bombay",
    seats: 36,
    seatsLeft: 8,
    category: "Scilab",
    level: "Intermediate",
    duration: "2 Days",
    description: "Model dynamic systems, responses, and stability using Scilab toolkits.",
  },
  {
    id: 17,
    title: "MATLAB for Image Processing",
    instructor: "Prof. Rajiv Soundararajan",
    date: "2025-06-25",
    location: "IIT Madras",
    seats: 34,
    seatsLeft: 10,
    category: "MATLAB",
    level: "Intermediate",
    duration: "1 Day",
    description: "Explore transforms, filters, segmentation, and image enhancement techniques.",
  },
  {
    id: 18,
    title: "AI for Students: Fast Track Bootcamp",
    instructor: "Prof. Sudeshna Sarkar",
    date: "2025-06-30",
    location: "IIT Kharagpur",
    seats: 70,
    seatsLeft: 26,
    category: "AI/ML",
    level: "Beginner",
    duration: "2 Days",
    description: "A high-energy introduction to modern AI concepts, workflows, and projects.",
  },
];
export default allWorkshops;